#!/bin/bash

# This is a really really badly written script that collects the files needed and assembles a few package types.

# Note: Requires everything ovm-ctl does, plus fakeroot, dpkg, tar, gzip

package="ovm-ctl"

if [ "$1" ]
then
	if [ "$1" = "--help" ]
	then
		echo "Usage: createdeb.$package [VERSION]"
		echo "VERSION defaults to adding 1 to last integer part of previous version number"
		exit 1
	fi

	version="$1"
else
	echo "Selecting new version number..."
	if [ -f "version" ]
	then
		oldversion=`cat "version"`
		# This next grabs the last numeric part of oldversion, in the form offset:value
		part=`echo "$oldversion" | egrep -bo '[0-9]+' | tail -n1`
		if [ "$part" ]
		then
			# Apologies for hacky code here. I decided to switch to python for this last bit.
			# This bit probably should be rewriten.
			version=` ( echo "$oldversion"; echo "$part" ) |
				python -c 's = raw_input(); offset, num = raw_input().split(":"); print s[:int(offset)] + str(int(num)+1) + s[int(offset)+len(num):]' `
		else # No numeric part found
			echo "Failed to increment version. Exiting."
			exit 1
		fi
	else
		echo "Failed to locate version file. Exiting."
		exit 1
	fi
	echo "Using version number $version"
fi

echo "Making directories"
activedir="$package-$version"
if ! mkdir "$activedir"
then
	echo Exiting
	exit 1
fi

echo "Copying/Generating files"
mkdir -p "$activedir/usr/share/ovm-ctl" &&
cp ../*.py "../extra" ../*.pem "$activedir/usr/share/ovm-ctl" -r &&
rm "$activedir/usr/share/ovm-ctl/"{gen_docs,man_writing}".py"
mkdir -p "$activedir/usr/bin" &&
cp "../ovm-ctl" "$activedir/usr/bin" -r &&
mkdir -p "$activedir/usr/share/man/man1" &&
echo "VERSION = r'$version'" > "$activedir/usr/share/ovm-ctl/version.py" &&
( cd ..; python "gen_docs.py" ) > "$activedir/usr/share/man/man1/ovm-ctl.1" || {
	echo Exiting
	exit 1
}

echo "Making tarball"
tar -cf "$activedir.tar" "$activedir" &&
tar -rf "$activedir.tar" "../README" &&
gzip "$activedir.tar" || {
	echo Exiting
	exit 1
}
md5sum "$activedir.tar.gz" > "$activedir.tar.gz.md5"
cp "$activedir.tar.gz" "ovm-ctl-latest.tar.gz"
cp "$activedir.tar.gz.md5" "ovm-ctl-latest.tar.gz.md5"

echo "Creating rpm - NOT IMPLEMENTED"
# TODO
true || { # Replace true with success condition
	echo Exiting
	exit 1
}

echo "Writing DEBIAN metadata"
# Note that DEBIAN/control does not contain any version info. So we append it.
mkdir "$activedir/DEBIAN" &&
cp DEBIAN/* "$activedir/DEBIAN/" -r &&
echo "Version: $version" >> "$activedir/DEBIAN/control" || {
	echo Exiting
	exit 1
}

echo "Making debian package"
fakeroot dpkg-deb -b "$activedir" || {
	echo Exiting
	exit 1
}
md5sum "$activedir.deb" > "$activedir.deb.md5"
cp "$activedir.deb" "ovm-ctl-latest.deb"
cp "$activedir.deb.md5" "ovm-ctl-latest.deb.md5"

echo -n "$version" > version

if git status > /dev/null 2>&1
then
	echo "Adding files to repository"
	git add $activedir*
fi

echo "Success!"
